secrets:
  postgres_pass:
    file: ./secrets/postgres_pass.txt

networks:
  rwa:
    name: rwa
    driver: bridge

services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_init:/docker-entrypoint-initdb.d
    secrets:
      - postgres_pass
    ports:
      - "5432:5432"
    networks:
      - rwa

  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: "postgres"
    ports:
      - 5050:8080
    depends_on:
      - postgres
    networks:
      - rwa

  redis:
    image: redis:alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - rwa

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      REDIS_HOSTS: "local:redis:6379"
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - rwa