secrets:
  postgres_pass:
    file: ./secrets/postgres_pass.txt

networks:
  rwa:
    name: rwa
    driver: bridge

services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_init:/docker-entrypoint-initdb.d
    secrets:
      - postgres_pass
    ports:
      - "5432:5432"
    networks:
      - rwa

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 5050:8080
    networks:
      - rwa
